# Generated by Django 5.2.7 on 2025-10-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
